// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AccountLoginRow {
    pub identity: __sdk::Identity,
    pub account_id: u64,
    pub login_method: String,
    pub steam_id: String,
    pub linked_at: __sdk::Timestamp,
}

impl __sdk::InModule for AccountLoginRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AccountLoginRow`.
///
/// Provides typed access to columns for query building.
pub struct AccountLoginRowCols {
    pub identity: __sdk::__query_builder::Col<AccountLoginRow, __sdk::Identity>,
    pub account_id: __sdk::__query_builder::Col<AccountLoginRow, u64>,
    pub login_method: __sdk::__query_builder::Col<AccountLoginRow, String>,
    pub steam_id: __sdk::__query_builder::Col<AccountLoginRow, String>,
    pub linked_at: __sdk::__query_builder::Col<AccountLoginRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AccountLoginRow {
    type Cols = AccountLoginRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccountLoginRowCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            login_method: __sdk::__query_builder::Col::new(table_name, "login_method"),
            steam_id: __sdk::__query_builder::Col::new(table_name, "steam_id"),
            linked_at: __sdk::__query_builder::Col::new(table_name, "linked_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AccountLoginRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct AccountLoginRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<AccountLoginRow, u64>,
    pub identity: __sdk::__query_builder::IxCol<AccountLoginRow, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for AccountLoginRow {
    type IxCols = AccountLoginRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AccountLoginRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AccountLoginRow {}
