// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AvatarMotionRow {
    pub account_id: u64,
    pub room_id: u64,
    pub zone: i32,
    pub mode: u8,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
    pub speed: f32,
    pub turn_rate: f32,
    pub client_time: f64,
    pub server_time: __sdk::Timestamp,
}

impl __sdk::InModule for AvatarMotionRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AvatarMotionRow`.
///
/// Provides typed access to columns for query building.
pub struct AvatarMotionRowCols {
    pub account_id: __sdk::__query_builder::Col<AvatarMotionRow, u64>,
    pub room_id: __sdk::__query_builder::Col<AvatarMotionRow, u64>,
    pub zone: __sdk::__query_builder::Col<AvatarMotionRow, i32>,
    pub mode: __sdk::__query_builder::Col<AvatarMotionRow, u8>,
    pub x: __sdk::__query_builder::Col<AvatarMotionRow, f32>,
    pub y: __sdk::__query_builder::Col<AvatarMotionRow, f32>,
    pub z: __sdk::__query_builder::Col<AvatarMotionRow, f32>,
    pub yaw: __sdk::__query_builder::Col<AvatarMotionRow, f32>,
    pub speed: __sdk::__query_builder::Col<AvatarMotionRow, f32>,
    pub turn_rate: __sdk::__query_builder::Col<AvatarMotionRow, f32>,
    pub client_time: __sdk::__query_builder::Col<AvatarMotionRow, f64>,
    pub server_time: __sdk::__query_builder::Col<AvatarMotionRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AvatarMotionRow {
    type Cols = AvatarMotionRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AvatarMotionRowCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            zone: __sdk::__query_builder::Col::new(table_name, "zone"),
            mode: __sdk::__query_builder::Col::new(table_name, "mode"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            speed: __sdk::__query_builder::Col::new(table_name, "speed"),
            turn_rate: __sdk::__query_builder::Col::new(table_name, "turn_rate"),
            client_time: __sdk::__query_builder::Col::new(table_name, "client_time"),
            server_time: __sdk::__query_builder::Col::new(table_name, "server_time"),
        }
    }
}

/// Indexed column accessor struct for the table `AvatarMotionRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct AvatarMotionRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<AvatarMotionRow, u64>,
    pub room_id: __sdk::__query_builder::IxCol<AvatarMotionRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for AvatarMotionRow {
    type IxCols = AvatarMotionRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AvatarMotionRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AvatarMotionRow {}
