// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::avatar_motion_row_type::AvatarMotionRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `avatar_motion`.
///
/// Obtain a handle from the [`AvatarMotionTableAccess::avatar_motion`] method on [`super::RemoteTables`],
/// like `ctx.db.avatar_motion()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.avatar_motion().on_insert(...)`.
pub struct AvatarMotionTableHandle<'ctx> {
    imp: __sdk::TableHandle<AvatarMotionRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `avatar_motion`.
pub struct AvatarMotionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AvatarMotionTableAccessor {
    type Row = AvatarMotionRow;
    type Handle<'db> = AvatarMotionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.avatar_motion()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `avatar_motion`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AvatarMotionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AvatarMotionTableHandle`], which mediates access to the table `avatar_motion`.
    fn avatar_motion(&self) -> AvatarMotionTableHandle<'_>;
}

impl AvatarMotionTableAccess for super::RemoteTables {
    fn avatar_motion(&self) -> AvatarMotionTableHandle<'_> {
        AvatarMotionTableHandle {
            imp: self.imp.get_table::<AvatarMotionRow>("avatar_motion"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AvatarMotionInsertCallbackId(__sdk::CallbackId);
pub struct AvatarMotionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AvatarMotionTableHandle<'ctx> {
    type Row = AvatarMotionRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AvatarMotionRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AvatarMotionTableHandle<'ctx> {
    type Row = AvatarMotionRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AvatarMotionRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AvatarMotionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AvatarMotionInsertCallbackId {
        AvatarMotionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AvatarMotionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AvatarMotionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AvatarMotionDeleteCallbackId {
        AvatarMotionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AvatarMotionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AvatarMotionTableHandle<'ctx> {
    type InsertCallbackId = AvatarMotionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AvatarMotionInsertCallbackId {
        AvatarMotionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AvatarMotionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AvatarMotionTableHandle<'ctx> {
    type DeleteCallbackId = AvatarMotionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AvatarMotionDeleteCallbackId {
        AvatarMotionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AvatarMotionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AvatarMotionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AvatarMotionTableHandle<'ctx> {
    type UpdateCallbackId = AvatarMotionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AvatarMotionUpdateCallbackId {
        AvatarMotionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AvatarMotionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AvatarMotionTableHandle<'ctx> {
    type UpdateCallbackId = AvatarMotionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AvatarMotionUpdateCallbackId {
        AvatarMotionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AvatarMotionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `account_id` unique index on the table `avatar_motion`,
/// which allows point queries on the field of the same name
/// via the [`AvatarMotionAccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.avatar_motion().account_id().find(...)`.
pub struct AvatarMotionAccountIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AvatarMotionRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AvatarMotionTableHandle<'ctx> {
    /// Get a handle on the `account_id` unique index on the table `avatar_motion`.
    pub fn account_id(&self) -> AvatarMotionAccountIdUnique<'ctx> {
        AvatarMotionAccountIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("account_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AvatarMotionAccountIdUnique<'ctx> {
    /// Find the subscribed row whose `account_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AvatarMotionRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AvatarMotionRow>("avatar_motion");
    _table.add_unique_constraint::<u64>("account_id", |row| &row.account_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AvatarMotionRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AvatarMotionRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AvatarMotionRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait avatar_motionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AvatarMotionRow`.
    fn avatar_motion(&self) -> __sdk::__query_builder::Table<AvatarMotionRow>;
}

impl avatar_motionQueryTableAccess for __sdk::QueryTableAccessor {
    fn avatar_motion(&self) -> __sdk::__query_builder::Table<AvatarMotionRow> {
        __sdk::__query_builder::Table::new("avatar_motion")
    }
}
