// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ball_row_type::BallRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ball`.
///
/// Obtain a handle from the [`BallTableAccess::ball`] method on [`super::RemoteTables`],
/// like `ctx.db.ball()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ball().on_insert(...)`.
pub struct BallTableHandle<'ctx> {
    imp: __sdk::TableHandle<BallRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `ball`.
pub struct BallTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for BallTableAccessor {
    type Row = BallRow;
    type Handle<'db> = BallTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.ball()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ball`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BallTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BallTableHandle`], which mediates access to the table `ball`.
    fn ball(&self) -> BallTableHandle<'_>;
}

impl BallTableAccess for super::RemoteTables {
    fn ball(&self) -> BallTableHandle<'_> {
        BallTableHandle {
            imp: self.imp.get_table::<BallRow>("ball"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BallInsertCallbackId(__sdk::CallbackId);
pub struct BallDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for BallTableHandle<'ctx> {
    type Row = BallRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BallRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for BallTableHandle<'ctx> {
    type Row = BallRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BallRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BallInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BallInsertCallbackId {
        BallInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BallInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BallDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BallDeleteCallbackId {
        BallDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BallDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for BallTableHandle<'ctx> {
    type InsertCallbackId = BallInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BallInsertCallbackId {
        BallInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BallInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for BallTableHandle<'ctx> {
    type DeleteCallbackId = BallDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BallDeleteCallbackId {
        BallDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BallDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BallUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BallTableHandle<'ctx> {
    type UpdateCallbackId = BallUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BallUpdateCallbackId {
        BallUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BallUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for BallTableHandle<'ctx> {
    type UpdateCallbackId = BallUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BallUpdateCallbackId {
        BallUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BallUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `account_id` unique index on the table `ball`,
/// which allows point queries on the field of the same name
/// via the [`BallAccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ball().account_id().find(...)`.
pub struct BallAccountIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BallRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BallTableHandle<'ctx> {
    /// Get a handle on the `account_id` unique index on the table `ball`.
    pub fn account_id(&self) -> BallAccountIdUnique<'ctx> {
        BallAccountIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("account_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BallAccountIdUnique<'ctx> {
    /// Find the subscribed row whose `account_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<BallRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BallRow>("ball");
    _table.add_unique_constraint::<u64>("account_id", |row| &row.account_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BallRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BallRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BallRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ballQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BallRow`.
    fn ball(&self) -> __sdk::__query_builder::Table<BallRow>;
}

impl ballQueryTableAccess for __sdk::QueryTableAccessor {
    fn ball(&self) -> __sdk::__query_builder::Table<BallRow> {
        __sdk::__query_builder::Table::new("ball")
    }
}
