// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BallRow {
    pub account_id: u64,
    pub room_id: u64,
    pub zone: i32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub stroke_count: i32,
    pub last_wind_time: f32,
    pub rests_at: __sdk::Timestamp,
}

impl __sdk::InModule for BallRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BallRow`.
///
/// Provides typed access to columns for query building.
pub struct BallRowCols {
    pub account_id: __sdk::__query_builder::Col<BallRow, u64>,
    pub room_id: __sdk::__query_builder::Col<BallRow, u64>,
    pub zone: __sdk::__query_builder::Col<BallRow, i32>,
    pub x: __sdk::__query_builder::Col<BallRow, f32>,
    pub y: __sdk::__query_builder::Col<BallRow, f32>,
    pub z: __sdk::__query_builder::Col<BallRow, f32>,
    pub stroke_count: __sdk::__query_builder::Col<BallRow, i32>,
    pub last_wind_time: __sdk::__query_builder::Col<BallRow, f32>,
    pub rests_at: __sdk::__query_builder::Col<BallRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for BallRow {
    type Cols = BallRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BallRowCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            zone: __sdk::__query_builder::Col::new(table_name, "zone"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            stroke_count: __sdk::__query_builder::Col::new(table_name, "stroke_count"),
            last_wind_time: __sdk::__query_builder::Col::new(table_name, "last_wind_time"),
            rests_at: __sdk::__query_builder::Col::new(table_name, "rests_at"),
        }
    }
}

/// Indexed column accessor struct for the table `BallRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct BallRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<BallRow, u64>,
    pub room_id: __sdk::__query_builder::IxCol<BallRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for BallRow {
    type IxCols = BallRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BallRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BallRow {}
