// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::collected_row_type::CollectedRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `collected`.
///
/// Obtain a handle from the [`CollectedTableAccess::collected`] method on [`super::RemoteTables`],
/// like `ctx.db.collected()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.collected().on_insert(...)`.
pub struct CollectedTableHandle<'ctx> {
    imp: __sdk::TableHandle<CollectedRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `collected`.
pub struct CollectedTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CollectedTableAccessor {
    type Row = CollectedRow;
    type Handle<'db> = CollectedTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.collected()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `collected`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CollectedTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CollectedTableHandle`], which mediates access to the table `collected`.
    fn collected(&self) -> CollectedTableHandle<'_>;
}

impl CollectedTableAccess for super::RemoteTables {
    fn collected(&self) -> CollectedTableHandle<'_> {
        CollectedTableHandle {
            imp: self.imp.get_table::<CollectedRow>("collected"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CollectedInsertCallbackId(__sdk::CallbackId);
pub struct CollectedDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CollectedTableHandle<'ctx> {
    type Row = CollectedRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CollectedRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for CollectedTableHandle<'ctx> {
    type Row = CollectedRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CollectedRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CollectedInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CollectedInsertCallbackId {
        CollectedInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CollectedInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CollectedDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CollectedDeleteCallbackId {
        CollectedDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CollectedDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CollectedTableHandle<'ctx> {
    type InsertCallbackId = CollectedInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CollectedInsertCallbackId {
        CollectedInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CollectedInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CollectedTableHandle<'ctx> {
    type DeleteCallbackId = CollectedDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CollectedDeleteCallbackId {
        CollectedDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CollectedDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CollectedUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CollectedTableHandle<'ctx> {
    type UpdateCallbackId = CollectedUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CollectedUpdateCallbackId {
        CollectedUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CollectedUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CollectedTableHandle<'ctx> {
    type UpdateCallbackId = CollectedUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CollectedUpdateCallbackId {
        CollectedUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CollectedUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `collected`,
/// which allows point queries on the field of the same name
/// via the [`CollectedIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.collected().id().find(...)`.
pub struct CollectedIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CollectedRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CollectedTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `collected`.
    pub fn id(&self) -> CollectedIdUnique<'ctx> {
        CollectedIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CollectedIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CollectedRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CollectedRow>("collected");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CollectedRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CollectedRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CollectedRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait collectedQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CollectedRow`.
    fn collected(&self) -> __sdk::__query_builder::Table<CollectedRow>;
}

impl collectedQueryTableAccess for __sdk::QueryTableAccessor {
    fn collected(&self) -> __sdk::__query_builder::Table<CollectedRow> {
        __sdk::__query_builder::Table::new("collected")
    }
}
