// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CollectedRow {
    pub id: u64,
    pub account_id: u64,
    pub collectible_id: String,
    pub repeatable: bool,
    pub claim_count: i32,
    pub claimed_at_holes_completed: i32,
}

impl __sdk::InModule for CollectedRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CollectedRow`.
///
/// Provides typed access to columns for query building.
pub struct CollectedRowCols {
    pub id: __sdk::__query_builder::Col<CollectedRow, u64>,
    pub account_id: __sdk::__query_builder::Col<CollectedRow, u64>,
    pub collectible_id: __sdk::__query_builder::Col<CollectedRow, String>,
    pub repeatable: __sdk::__query_builder::Col<CollectedRow, bool>,
    pub claim_count: __sdk::__query_builder::Col<CollectedRow, i32>,
    pub claimed_at_holes_completed: __sdk::__query_builder::Col<CollectedRow, i32>,
}

impl __sdk::__query_builder::HasCols for CollectedRow {
    type Cols = CollectedRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CollectedRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            collectible_id: __sdk::__query_builder::Col::new(table_name, "collectible_id"),
            repeatable: __sdk::__query_builder::Col::new(table_name, "repeatable"),
            claim_count: __sdk::__query_builder::Col::new(table_name, "claim_count"),
            claimed_at_holes_completed: __sdk::__query_builder::Col::new(
                table_name,
                "claimed_at_holes_completed",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `CollectedRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct CollectedRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<CollectedRow, u64>,
    pub id: __sdk::__query_builder::IxCol<CollectedRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for CollectedRow {
    type IxCols = CollectedRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CollectedRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CollectedRow {}
