// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::completed_course_row_type::CompletedCourseRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `completed_course`.
///
/// Obtain a handle from the [`CompletedCourseTableAccess::completed_course`] method on [`super::RemoteTables`],
/// like `ctx.db.completed_course()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.completed_course().on_insert(...)`.
pub struct CompletedCourseTableHandle<'ctx> {
    imp: __sdk::TableHandle<CompletedCourseRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `completed_course`.
pub struct CompletedCourseTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CompletedCourseTableAccessor {
    type Row = CompletedCourseRow;
    type Handle<'db> = CompletedCourseTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.completed_course()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `completed_course`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CompletedCourseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CompletedCourseTableHandle`], which mediates access to the table `completed_course`.
    fn completed_course(&self) -> CompletedCourseTableHandle<'_>;
}

impl CompletedCourseTableAccess for super::RemoteTables {
    fn completed_course(&self) -> CompletedCourseTableHandle<'_> {
        CompletedCourseTableHandle {
            imp: self.imp.get_table::<CompletedCourseRow>("completed_course"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CompletedCourseInsertCallbackId(__sdk::CallbackId);
pub struct CompletedCourseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CompletedCourseTableHandle<'ctx> {
    type Row = CompletedCourseRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CompletedCourseRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for CompletedCourseTableHandle<'ctx> {
    type Row = CompletedCourseRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CompletedCourseRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CompletedCourseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CompletedCourseInsertCallbackId {
        CompletedCourseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CompletedCourseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CompletedCourseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CompletedCourseDeleteCallbackId {
        CompletedCourseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CompletedCourseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CompletedCourseTableHandle<'ctx> {
    type InsertCallbackId = CompletedCourseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CompletedCourseInsertCallbackId {
        CompletedCourseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CompletedCourseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CompletedCourseTableHandle<'ctx> {
    type DeleteCallbackId = CompletedCourseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CompletedCourseDeleteCallbackId {
        CompletedCourseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CompletedCourseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CompletedCourseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CompletedCourseTableHandle<'ctx> {
    type UpdateCallbackId = CompletedCourseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CompletedCourseUpdateCallbackId {
        CompletedCourseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CompletedCourseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CompletedCourseTableHandle<'ctx> {
    type UpdateCallbackId = CompletedCourseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CompletedCourseUpdateCallbackId {
        CompletedCourseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CompletedCourseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `completed_course`,
/// which allows point queries on the field of the same name
/// via the [`CompletedCourseIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.completed_course().id().find(...)`.
pub struct CompletedCourseIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CompletedCourseRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CompletedCourseTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `completed_course`.
    pub fn id(&self) -> CompletedCourseIdUnique<'ctx> {
        CompletedCourseIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CompletedCourseIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CompletedCourseRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CompletedCourseRow>("completed_course");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CompletedCourseRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CompletedCourseRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CompletedCourseRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait completed_courseQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CompletedCourseRow`.
    fn completed_course(&self) -> __sdk::__query_builder::Table<CompletedCourseRow>;
}

impl completed_courseQueryTableAccess for __sdk::QueryTableAccessor {
    fn completed_course(&self) -> __sdk::__query_builder::Table<CompletedCourseRow> {
        __sdk::__query_builder::Table::new("completed_course")
    }
}
