// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CompletedCourseRow {
    pub id: u64,
    pub account_id: u64,
    pub course_id: String,
    pub at: __sdk::Timestamp,
}

impl __sdk::InModule for CompletedCourseRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CompletedCourseRow`.
///
/// Provides typed access to columns for query building.
pub struct CompletedCourseRowCols {
    pub id: __sdk::__query_builder::Col<CompletedCourseRow, u64>,
    pub account_id: __sdk::__query_builder::Col<CompletedCourseRow, u64>,
    pub course_id: __sdk::__query_builder::Col<CompletedCourseRow, String>,
    pub at: __sdk::__query_builder::Col<CompletedCourseRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for CompletedCourseRow {
    type Cols = CompletedCourseRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CompletedCourseRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            course_id: __sdk::__query_builder::Col::new(table_name, "course_id"),
            at: __sdk::__query_builder::Col::new(table_name, "at"),
        }
    }
}

/// Indexed column accessor struct for the table `CompletedCourseRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct CompletedCourseRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<CompletedCourseRow, u64>,
    pub id: __sdk::__query_builder::IxCol<CompletedCourseRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for CompletedCourseRow {
    type IxCols = CompletedCourseRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CompletedCourseRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CompletedCourseRow {}
