// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CupBallRow {
    pub account_id: u64,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl __sdk::InModule for CupBallRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CupBallRow`.
///
/// Provides typed access to columns for query building.
pub struct CupBallRowCols {
    pub account_id: __sdk::__query_builder::Col<CupBallRow, u64>,
    pub x: __sdk::__query_builder::Col<CupBallRow, f32>,
    pub y: __sdk::__query_builder::Col<CupBallRow, f32>,
    pub z: __sdk::__query_builder::Col<CupBallRow, f32>,
}

impl __sdk::__query_builder::HasCols for CupBallRow {
    type Cols = CupBallRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CupBallRowCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
        }
    }
}

/// Indexed column accessor struct for the table `CupBallRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct CupBallRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<CupBallRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for CupBallRow {
    type IxCols = CupBallRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CupBallRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CupBallRow {}
