// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EmoteEventRow {
    pub room_id: u64,
    pub account_id: u64,
    pub emote_id: String,
}

impl __sdk::InModule for EmoteEventRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EmoteEventRow`.
///
/// Provides typed access to columns for query building.
pub struct EmoteEventRowCols {
    pub room_id: __sdk::__query_builder::Col<EmoteEventRow, u64>,
    pub account_id: __sdk::__query_builder::Col<EmoteEventRow, u64>,
    pub emote_id: __sdk::__query_builder::Col<EmoteEventRow, String>,
}

impl __sdk::__query_builder::HasCols for EmoteEventRow {
    type Cols = EmoteEventRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EmoteEventRowCols {
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            emote_id: __sdk::__query_builder::Col::new(table_name, "emote_id"),
        }
    }
}

/// Indexed column accessor struct for the table `EmoteEventRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct EmoteEventRowIxCols {
    pub room_id: __sdk::__query_builder::IxCol<EmoteEventRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for EmoteEventRow {
    type IxCols = EmoteEventRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EmoteEventRowIxCols {
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}
