// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EnterHoleArgs {
    pub hole_index: i32,
}

impl From<EnterHoleArgs> for super::Reducer {
    fn from(args: EnterHoleArgs) -> Self {
        Self::EnterHole {
            hole_index: args.hole_index,
        }
    }
}

impl __sdk::InModule for EnterHoleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `enter_hole`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait enter_hole {
    /// Request that the remote module invoke the reducer `enter_hole` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`enter_hole:enter_hole_then`] to run a callback after the reducer completes.
    fn enter_hole(&self, hole_index: i32) -> __sdk::Result<()> {
        self.enter_hole_then(hole_index, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `enter_hole` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn enter_hole_then(
        &self,
        hole_index: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl enter_hole for super::RemoteReducers {
    fn enter_hole_then(
        &self,
        hole_index: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EnterHoleArgs { hole_index }, callback)
    }
}
