// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GolfGroupRow {
    pub group_id: u64,
    pub room_id: u64,
    pub leader: u64,
    pub member_count: i32,
}

impl __sdk::InModule for GolfGroupRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GolfGroupRow`.
///
/// Provides typed access to columns for query building.
pub struct GolfGroupRowCols {
    pub group_id: __sdk::__query_builder::Col<GolfGroupRow, u64>,
    pub room_id: __sdk::__query_builder::Col<GolfGroupRow, u64>,
    pub leader: __sdk::__query_builder::Col<GolfGroupRow, u64>,
    pub member_count: __sdk::__query_builder::Col<GolfGroupRow, i32>,
}

impl __sdk::__query_builder::HasCols for GolfGroupRow {
    type Cols = GolfGroupRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GolfGroupRowCols {
            group_id: __sdk::__query_builder::Col::new(table_name, "group_id"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            leader: __sdk::__query_builder::Col::new(table_name, "leader"),
            member_count: __sdk::__query_builder::Col::new(table_name, "member_count"),
        }
    }
}

/// Indexed column accessor struct for the table `GolfGroupRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct GolfGroupRowIxCols {
    pub group_id: __sdk::__query_builder::IxCol<GolfGroupRow, u64>,
    pub room_id: __sdk::__query_builder::IxCol<GolfGroupRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for GolfGroupRow {
    type IxCols = GolfGroupRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GolfGroupRowIxCols {
            group_id: __sdk::__query_builder::IxCol::new(table_name, "group_id"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GolfGroupRow {}
