// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::golf_group_row_type::GolfGroupRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `golf_group`.
///
/// Obtain a handle from the [`GolfGroupTableAccess::golf_group`] method on [`super::RemoteTables`],
/// like `ctx.db.golf_group()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.golf_group().on_insert(...)`.
pub struct GolfGroupTableHandle<'ctx> {
    imp: __sdk::TableHandle<GolfGroupRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `golf_group`.
pub struct GolfGroupTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GolfGroupTableAccessor {
    type Row = GolfGroupRow;
    type Handle<'db> = GolfGroupTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.golf_group()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `golf_group`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GolfGroupTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GolfGroupTableHandle`], which mediates access to the table `golf_group`.
    fn golf_group(&self) -> GolfGroupTableHandle<'_>;
}

impl GolfGroupTableAccess for super::RemoteTables {
    fn golf_group(&self) -> GolfGroupTableHandle<'_> {
        GolfGroupTableHandle {
            imp: self.imp.get_table::<GolfGroupRow>("golf_group"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GolfGroupInsertCallbackId(__sdk::CallbackId);
pub struct GolfGroupDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GolfGroupTableHandle<'ctx> {
    type Row = GolfGroupRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GolfGroupRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GolfGroupTableHandle<'ctx> {
    type Row = GolfGroupRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GolfGroupRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GolfGroupInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GolfGroupInsertCallbackId {
        GolfGroupInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GolfGroupInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GolfGroupDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GolfGroupDeleteCallbackId {
        GolfGroupDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GolfGroupDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GolfGroupTableHandle<'ctx> {
    type InsertCallbackId = GolfGroupInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GolfGroupInsertCallbackId {
        GolfGroupInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GolfGroupInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GolfGroupTableHandle<'ctx> {
    type DeleteCallbackId = GolfGroupDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GolfGroupDeleteCallbackId {
        GolfGroupDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GolfGroupDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GolfGroupUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GolfGroupTableHandle<'ctx> {
    type UpdateCallbackId = GolfGroupUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GolfGroupUpdateCallbackId {
        GolfGroupUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GolfGroupUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GolfGroupTableHandle<'ctx> {
    type UpdateCallbackId = GolfGroupUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GolfGroupUpdateCallbackId {
        GolfGroupUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GolfGroupUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `group_id` unique index on the table `golf_group`,
/// which allows point queries on the field of the same name
/// via the [`GolfGroupGroupIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.golf_group().group_id().find(...)`.
pub struct GolfGroupGroupIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GolfGroupRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GolfGroupTableHandle<'ctx> {
    /// Get a handle on the `group_id` unique index on the table `golf_group`.
    pub fn group_id(&self) -> GolfGroupGroupIdUnique<'ctx> {
        GolfGroupGroupIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("group_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GolfGroupGroupIdUnique<'ctx> {
    /// Find the subscribed row whose `group_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GolfGroupRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GolfGroupRow>("golf_group");
    _table.add_unique_constraint::<u64>("group_id", |row| &row.group_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GolfGroupRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GolfGroupRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GolfGroupRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait golf_groupQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GolfGroupRow`.
    fn golf_group(&self) -> __sdk::__query_builder::Table<GolfGroupRow>;
}

impl golf_groupQueryTableAccess for __sdk::QueryTableAccessor {
    fn golf_group(&self) -> __sdk::__query_builder::Table<GolfGroupRow> {
        __sdk::__query_builder::Table::new("golf_group")
    }
}
