// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HoleScoreRow {
    pub id: u64,
    pub account_id: u64,
    pub course_id: String,
    pub hole_index: i32,
    pub strokes: i32,
    pub par: i32,
    pub at: __sdk::Timestamp,
}

impl __sdk::InModule for HoleScoreRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HoleScoreRow`.
///
/// Provides typed access to columns for query building.
pub struct HoleScoreRowCols {
    pub id: __sdk::__query_builder::Col<HoleScoreRow, u64>,
    pub account_id: __sdk::__query_builder::Col<HoleScoreRow, u64>,
    pub course_id: __sdk::__query_builder::Col<HoleScoreRow, String>,
    pub hole_index: __sdk::__query_builder::Col<HoleScoreRow, i32>,
    pub strokes: __sdk::__query_builder::Col<HoleScoreRow, i32>,
    pub par: __sdk::__query_builder::Col<HoleScoreRow, i32>,
    pub at: __sdk::__query_builder::Col<HoleScoreRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for HoleScoreRow {
    type Cols = HoleScoreRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HoleScoreRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            course_id: __sdk::__query_builder::Col::new(table_name, "course_id"),
            hole_index: __sdk::__query_builder::Col::new(table_name, "hole_index"),
            strokes: __sdk::__query_builder::Col::new(table_name, "strokes"),
            par: __sdk::__query_builder::Col::new(table_name, "par"),
            at: __sdk::__query_builder::Col::new(table_name, "at"),
        }
    }
}

/// Indexed column accessor struct for the table `HoleScoreRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct HoleScoreRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<HoleScoreRow, u64>,
    pub id: __sdk::__query_builder::IxCol<HoleScoreRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for HoleScoreRow {
    type IxCols = HoleScoreRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HoleScoreRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for HoleScoreRow {}
