// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::hole_score_row_type::HoleScoreRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `hole_score`.
///
/// Obtain a handle from the [`HoleScoreTableAccess::hole_score`] method on [`super::RemoteTables`],
/// like `ctx.db.hole_score()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hole_score().on_insert(...)`.
pub struct HoleScoreTableHandle<'ctx> {
    imp: __sdk::TableHandle<HoleScoreRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `hole_score`.
pub struct HoleScoreTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for HoleScoreTableAccessor {
    type Row = HoleScoreRow;
    type Handle<'db> = HoleScoreTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.hole_score()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `hole_score`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HoleScoreTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HoleScoreTableHandle`], which mediates access to the table `hole_score`.
    fn hole_score(&self) -> HoleScoreTableHandle<'_>;
}

impl HoleScoreTableAccess for super::RemoteTables {
    fn hole_score(&self) -> HoleScoreTableHandle<'_> {
        HoleScoreTableHandle {
            imp: self.imp.get_table::<HoleScoreRow>("hole_score"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HoleScoreInsertCallbackId(__sdk::CallbackId);
pub struct HoleScoreDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for HoleScoreTableHandle<'ctx> {
    type Row = HoleScoreRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HoleScoreRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for HoleScoreTableHandle<'ctx> {
    type Row = HoleScoreRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HoleScoreRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HoleScoreInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HoleScoreInsertCallbackId {
        HoleScoreInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HoleScoreInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HoleScoreDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HoleScoreDeleteCallbackId {
        HoleScoreDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HoleScoreDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for HoleScoreTableHandle<'ctx> {
    type InsertCallbackId = HoleScoreInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HoleScoreInsertCallbackId {
        HoleScoreInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HoleScoreInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for HoleScoreTableHandle<'ctx> {
    type DeleteCallbackId = HoleScoreDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HoleScoreDeleteCallbackId {
        HoleScoreDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HoleScoreDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct HoleScoreUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for HoleScoreTableHandle<'ctx> {
    type UpdateCallbackId = HoleScoreUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HoleScoreUpdateCallbackId {
        HoleScoreUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HoleScoreUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for HoleScoreTableHandle<'ctx> {
    type UpdateCallbackId = HoleScoreUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HoleScoreUpdateCallbackId {
        HoleScoreUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HoleScoreUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `hole_score`,
/// which allows point queries on the field of the same name
/// via the [`HoleScoreIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hole_score().id().find(...)`.
pub struct HoleScoreIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<HoleScoreRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> HoleScoreTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `hole_score`.
    pub fn id(&self) -> HoleScoreIdUnique<'ctx> {
        HoleScoreIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> HoleScoreIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<HoleScoreRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<HoleScoreRow>("hole_score");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<HoleScoreRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<HoleScoreRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `HoleScoreRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait hole_scoreQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `HoleScoreRow`.
    fn hole_score(&self) -> __sdk::__query_builder::Table<HoleScoreRow>;
}

impl hole_scoreQueryTableAccess for __sdk::QueryTableAccessor {
    fn hole_score(&self) -> __sdk::__query_builder::Table<HoleScoreRow> {
        __sdk::__query_builder::Table::new("hole_score")
    }
}
