// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LinkBudgetRow {
    pub account_id: u64,
    pub window_start: i64,
    pub count: u32,
}

impl __sdk::InModule for LinkBudgetRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LinkBudgetRow`.
///
/// Provides typed access to columns for query building.
pub struct LinkBudgetRowCols {
    pub account_id: __sdk::__query_builder::Col<LinkBudgetRow, u64>,
    pub window_start: __sdk::__query_builder::Col<LinkBudgetRow, i64>,
    pub count: __sdk::__query_builder::Col<LinkBudgetRow, u32>,
}

impl __sdk::__query_builder::HasCols for LinkBudgetRow {
    type Cols = LinkBudgetRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LinkBudgetRowCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            window_start: __sdk::__query_builder::Col::new(table_name, "window_start"),
            count: __sdk::__query_builder::Col::new(table_name, "count"),
        }
    }
}

/// Indexed column accessor struct for the table `LinkBudgetRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct LinkBudgetRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<LinkBudgetRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for LinkBudgetRow {
    type IxCols = LinkBudgetRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LinkBudgetRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LinkBudgetRow {}
