// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LinkCodeExpiryRow {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub code: String,
}

impl __sdk::InModule for LinkCodeExpiryRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LinkCodeExpiryRow`.
///
/// Provides typed access to columns for query building.
pub struct LinkCodeExpiryRowCols {
    pub scheduled_id: __sdk::__query_builder::Col<LinkCodeExpiryRow, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<LinkCodeExpiryRow, __sdk::ScheduleAt>,
    pub code: __sdk::__query_builder::Col<LinkCodeExpiryRow, String>,
}

impl __sdk::__query_builder::HasCols for LinkCodeExpiryRow {
    type Cols = LinkCodeExpiryRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LinkCodeExpiryRowCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            code: __sdk::__query_builder::Col::new(table_name, "code"),
        }
    }
}

/// Indexed column accessor struct for the table `LinkCodeExpiryRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct LinkCodeExpiryRowIxCols {
    pub code: __sdk::__query_builder::IxCol<LinkCodeExpiryRow, String>,
    pub scheduled_id: __sdk::__query_builder::IxCol<LinkCodeExpiryRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for LinkCodeExpiryRow {
    type IxCols = LinkCodeExpiryRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LinkCodeExpiryRowIxCols {
            code: __sdk::__query_builder::IxCol::new(table_name, "code"),
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LinkCodeExpiryRow {}
