// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LinkCodeRow {
    pub code: String,
    pub account_id: u64,
    pub expires_at: __sdk::Timestamp,
}

impl __sdk::InModule for LinkCodeRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LinkCodeRow`.
///
/// Provides typed access to columns for query building.
pub struct LinkCodeRowCols {
    pub code: __sdk::__query_builder::Col<LinkCodeRow, String>,
    pub account_id: __sdk::__query_builder::Col<LinkCodeRow, u64>,
    pub expires_at: __sdk::__query_builder::Col<LinkCodeRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for LinkCodeRow {
    type Cols = LinkCodeRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LinkCodeRowCols {
            code: __sdk::__query_builder::Col::new(table_name, "code"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `LinkCodeRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct LinkCodeRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<LinkCodeRow, u64>,
    pub code: __sdk::__query_builder::IxCol<LinkCodeRow, String>,
}

impl __sdk::__query_builder::HasIxCols for LinkCodeRow {
    type IxCols = LinkCodeRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LinkCodeRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            code: __sdk::__query_builder::IxCol::new(table_name, "code"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LinkCodeRow {}
