// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LinkAttemptRow {
    pub identity: __sdk::Identity,
    pub window_start: i64,
    pub failures: u32,
    pub last_result: String,
    pub last_at: __sdk::Timestamp,
}

impl __sdk::InModule for LinkAttemptRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LinkAttemptRow`.
///
/// Provides typed access to columns for query building.
pub struct LinkAttemptRowCols {
    pub identity: __sdk::__query_builder::Col<LinkAttemptRow, __sdk::Identity>,
    pub window_start: __sdk::__query_builder::Col<LinkAttemptRow, i64>,
    pub failures: __sdk::__query_builder::Col<LinkAttemptRow, u32>,
    pub last_result: __sdk::__query_builder::Col<LinkAttemptRow, String>,
    pub last_at: __sdk::__query_builder::Col<LinkAttemptRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for LinkAttemptRow {
    type Cols = LinkAttemptRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LinkAttemptRowCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            window_start: __sdk::__query_builder::Col::new(table_name, "window_start"),
            failures: __sdk::__query_builder::Col::new(table_name, "failures"),
            last_result: __sdk::__query_builder::Col::new(table_name, "last_result"),
            last_at: __sdk::__query_builder::Col::new(table_name, "last_at"),
        }
    }
}

/// Indexed column accessor struct for the table `LinkAttemptRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct LinkAttemptRowIxCols {
    pub identity: __sdk::__query_builder::IxCol<LinkAttemptRow, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for LinkAttemptRow {
    type IxCols = LinkAttemptRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LinkAttemptRowIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LinkAttemptRow {}
