// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LinkStatus {
    pub result: String,
    pub at: __sdk::Timestamp,
}

impl __sdk::InModule for LinkStatus {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LinkStatus`.
///
/// Provides typed access to columns for query building.
pub struct LinkStatusCols {
    pub result: __sdk::__query_builder::Col<LinkStatus, String>,
    pub at: __sdk::__query_builder::Col<LinkStatus, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for LinkStatus {
    type Cols = LinkStatusCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LinkStatusCols {
            result: __sdk::__query_builder::Col::new(table_name, "result"),
            at: __sdk::__query_builder::Col::new(table_name, "at"),
        }
    }
}
