// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LinkCodeView {
    pub code: String,
    pub expires_at: __sdk::Timestamp,
}

impl __sdk::InModule for LinkCodeView {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LinkCodeView`.
///
/// Provides typed access to columns for query building.
pub struct LinkCodeViewCols {
    pub code: __sdk::__query_builder::Col<LinkCodeView, String>,
    pub expires_at: __sdk::__query_builder::Col<LinkCodeView, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for LinkCodeView {
    type Cols = LinkCodeViewCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LinkCodeViewCols {
            code: __sdk::__query_builder::Col::new(table_name, "code"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}
