// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod account_login_row_type;
pub mod admin_set_config_reducer;
pub mod avatar_motion_row_type;
pub mod avatar_motion_table;
pub mod ball_row_type;
pub mod ball_table;
pub mod claim_collectible_reducer_reducer;
pub mod claim_name_reducer;
pub mod collected_row_type;
pub mod collected_table;
pub mod completed_course_row_type;
pub mod completed_course_table;
pub mod create_group_reducer;
pub mod create_link_code_reducer;
pub mod cup_ball_row_type;
pub mod emote_event_row_type;
pub mod emote_event_table;
pub mod emote_reducer;
pub mod enter_hole_reducer;
pub mod golf_group_row_type;
pub mod golf_group_table;
pub mod hole_score_row_type;
pub mod hole_score_table;
pub mod join_course_reducer;
pub mod join_group_reducer;
pub mod leave_group_reducer;
pub mod leave_room_reducer;
pub mod link_attempt_row_type;
pub mod link_budget_row_type;
pub mod link_code_expiry_row_type;
pub mod link_code_row_type;
pub mod link_code_view_type;
pub mod link_status_type;
pub mod motion_budget_row_type;
pub mod my_account_table;
pub mod my_link_code_table;
pub mod my_link_status_table;
pub mod pick_up_ball_reducer;
pub mod player_row_type;
pub mod player_skill_row_type;
pub mod player_skill_table;
pub mod player_table;
pub mod redeem_link_code_reducer;
pub mod retee_reducer;
pub mod return_to_hub_reducer;
pub mod room_member_row_type;
pub mod room_member_table;
pub mod room_row_type;
pub mod room_table;
pub mod server_config_row_type;
pub mod session_row_type;
pub mod shot_event_row_type;
pub mod shot_event_table;
pub mod take_shot_reducer;
pub mod update_motion_reducer;
pub mod world_flag_row_type;
pub mod world_flag_table;

pub use account_login_row_type::AccountLoginRow;
pub use admin_set_config_reducer::admin_set_config;
pub use avatar_motion_row_type::AvatarMotionRow;
pub use avatar_motion_table::*;
pub use ball_row_type::BallRow;
pub use ball_table::*;
pub use claim_collectible_reducer_reducer::claim_collectible_reducer;
pub use claim_name_reducer::claim_name;
pub use collected_row_type::CollectedRow;
pub use collected_table::*;
pub use completed_course_row_type::CompletedCourseRow;
pub use completed_course_table::*;
pub use create_group_reducer::create_group;
pub use create_link_code_reducer::create_link_code;
pub use cup_ball_row_type::CupBallRow;
pub use emote_event_row_type::EmoteEventRow;
pub use emote_event_table::*;
pub use emote_reducer::emote;
pub use enter_hole_reducer::enter_hole;
pub use golf_group_row_type::GolfGroupRow;
pub use golf_group_table::*;
pub use hole_score_row_type::HoleScoreRow;
pub use hole_score_table::*;
pub use join_course_reducer::join_course;
pub use join_group_reducer::join_group;
pub use leave_group_reducer::leave_group;
pub use leave_room_reducer::leave_room;
pub use link_attempt_row_type::LinkAttemptRow;
pub use link_budget_row_type::LinkBudgetRow;
pub use link_code_expiry_row_type::LinkCodeExpiryRow;
pub use link_code_row_type::LinkCodeRow;
pub use link_code_view_type::LinkCodeView;
pub use link_status_type::LinkStatus;
pub use motion_budget_row_type::MotionBudgetRow;
pub use my_account_table::*;
pub use my_link_code_table::*;
pub use my_link_status_table::*;
pub use pick_up_ball_reducer::pick_up_ball;
pub use player_row_type::PlayerRow;
pub use player_skill_row_type::PlayerSkillRow;
pub use player_skill_table::*;
pub use player_table::*;
pub use redeem_link_code_reducer::redeem_link_code;
pub use retee_reducer::retee;
pub use return_to_hub_reducer::return_to_hub;
pub use room_member_row_type::RoomMemberRow;
pub use room_member_table::*;
pub use room_row_type::RoomRow;
pub use room_table::*;
pub use server_config_row_type::ServerConfigRow;
pub use session_row_type::SessionRow;
pub use shot_event_row_type::ShotEventRow;
pub use shot_event_table::*;
pub use take_shot_reducer::take_shot;
pub use update_motion_reducer::update_motion;
pub use world_flag_row_type::WorldFlagRow;
pub use world_flag_table::*;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AdminSetConfig {
        auth_issuer: String,
        auth_audience: String,
        allow_anonymous: bool,
        steam_app_id: u32,
        allow_non_steam: bool,
        link_secret: String,
    },
    ClaimCollectibleReducer {
        collectible_id: String,
    },
    ClaimName {
        name: String,
    },
    CreateGroup,
    CreateLinkCode,
    Emote {
        emote_id: String,
    },
    EnterHole {
        hole_index: i32,
    },
    JoinCourse {
        course_id: String,
    },
    JoinGroup {
        group_id: u64,
    },
    LeaveGroup,
    LeaveRoom,
    PickUpBall,
    RedeemLinkCode {
        typed_code: String,
    },
    Retee,
    ReturnToHub,
    TakeShot {
        stroke: i32,
        aim_angle: f32,
        club_id: String,
        power: f32,
        cigarette_active: bool,
        wind_time: f32,
    },
    UpdateMotion {
        zone: i32,
        mode: u8,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,
        speed: f32,
        turn_rate: f32,
        client_time: f64,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AdminSetConfig { .. } => "admin_set_config",
            Reducer::ClaimCollectibleReducer { .. } => "claim_collectible",
            Reducer::ClaimName { .. } => "claim_name",
            Reducer::CreateGroup => "create_group",
            Reducer::CreateLinkCode => "create_link_code",
            Reducer::Emote { .. } => "emote",
            Reducer::EnterHole { .. } => "enter_hole",
            Reducer::JoinCourse { .. } => "join_course",
            Reducer::JoinGroup { .. } => "join_group",
            Reducer::LeaveGroup => "leave_group",
            Reducer::LeaveRoom => "leave_room",
            Reducer::PickUpBall => "pick_up_ball",
            Reducer::RedeemLinkCode { .. } => "redeem_link_code",
            Reducer::Retee => "retee",
            Reducer::ReturnToHub => "return_to_hub",
            Reducer::TakeShot { .. } => "take_shot",
            Reducer::UpdateMotion { .. } => "update_motion",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AdminSetConfig {
                auth_issuer,
                auth_audience,
                allow_anonymous,
                steam_app_id,
                allow_non_steam,
                link_secret,
            } => __sats::bsatn::to_vec(&admin_set_config_reducer::AdminSetConfigArgs {
                auth_issuer: auth_issuer.clone(),
                auth_audience: auth_audience.clone(),
                allow_anonymous: allow_anonymous.clone(),
                steam_app_id: steam_app_id.clone(),
                allow_non_steam: allow_non_steam.clone(),
                link_secret: link_secret.clone(),
            }),
            Reducer::ClaimCollectibleReducer { collectible_id } => __sats::bsatn::to_vec(
                &claim_collectible_reducer_reducer::ClaimCollectibleReducerArgs {
                    collectible_id: collectible_id.clone(),
                },
            ),
            Reducer::ClaimName { name } => {
                __sats::bsatn::to_vec(&claim_name_reducer::ClaimNameArgs { name: name.clone() })
            }
            Reducer::CreateGroup => {
                __sats::bsatn::to_vec(&create_group_reducer::CreateGroupArgs {})
            }
            Reducer::CreateLinkCode => {
                __sats::bsatn::to_vec(&create_link_code_reducer::CreateLinkCodeArgs {})
            }
            Reducer::Emote { emote_id } => __sats::bsatn::to_vec(&emote_reducer::EmoteArgs {
                emote_id: emote_id.clone(),
            }),
            Reducer::EnterHole { hole_index } => {
                __sats::bsatn::to_vec(&enter_hole_reducer::EnterHoleArgs {
                    hole_index: hole_index.clone(),
                })
            }
            Reducer::JoinCourse { course_id } => {
                __sats::bsatn::to_vec(&join_course_reducer::JoinCourseArgs {
                    course_id: course_id.clone(),
                })
            }
            Reducer::JoinGroup { group_id } => {
                __sats::bsatn::to_vec(&join_group_reducer::JoinGroupArgs {
                    group_id: group_id.clone(),
                })
            }
            Reducer::LeaveGroup => __sats::bsatn::to_vec(&leave_group_reducer::LeaveGroupArgs {}),
            Reducer::LeaveRoom => __sats::bsatn::to_vec(&leave_room_reducer::LeaveRoomArgs {}),
            Reducer::PickUpBall => __sats::bsatn::to_vec(&pick_up_ball_reducer::PickUpBallArgs {}),
            Reducer::RedeemLinkCode { typed_code } => {
                __sats::bsatn::to_vec(&redeem_link_code_reducer::RedeemLinkCodeArgs {
                    typed_code: typed_code.clone(),
                })
            }
            Reducer::Retee => __sats::bsatn::to_vec(&retee_reducer::ReteeArgs {}),
            Reducer::ReturnToHub => {
                __sats::bsatn::to_vec(&return_to_hub_reducer::ReturnToHubArgs {})
            }
            Reducer::TakeShot {
                stroke,
                aim_angle,
                club_id,
                power,
                cigarette_active,
                wind_time,
            } => __sats::bsatn::to_vec(&take_shot_reducer::TakeShotArgs {
                stroke: stroke.clone(),
                aim_angle: aim_angle.clone(),
                club_id: club_id.clone(),
                power: power.clone(),
                cigarette_active: cigarette_active.clone(),
                wind_time: wind_time.clone(),
            }),
            Reducer::UpdateMotion {
                zone,
                mode,
                x,
                y,
                z,
                yaw,
                speed,
                turn_rate,
                client_time,
            } => __sats::bsatn::to_vec(&update_motion_reducer::UpdateMotionArgs {
                zone: zone.clone(),
                mode: mode.clone(),
                x: x.clone(),
                y: y.clone(),
                z: z.clone(),
                yaw: yaw.clone(),
                speed: speed.clone(),
                turn_rate: turn_rate.clone(),
                client_time: client_time.clone(),
            }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    avatar_motion: __sdk::TableUpdate<AvatarMotionRow>,
    ball: __sdk::TableUpdate<BallRow>,
    collected: __sdk::TableUpdate<CollectedRow>,
    completed_course: __sdk::TableUpdate<CompletedCourseRow>,
    emote_event: __sdk::TableUpdate<EmoteEventRow>,
    golf_group: __sdk::TableUpdate<GolfGroupRow>,
    hole_score: __sdk::TableUpdate<HoleScoreRow>,
    my_account: __sdk::TableUpdate<PlayerRow>,
    my_link_code: __sdk::TableUpdate<LinkCodeView>,
    my_link_status: __sdk::TableUpdate<LinkStatus>,
    player: __sdk::TableUpdate<PlayerRow>,
    player_skill: __sdk::TableUpdate<PlayerSkillRow>,
    room: __sdk::TableUpdate<RoomRow>,
    room_member: __sdk::TableUpdate<RoomMemberRow>,
    shot_event: __sdk::TableUpdate<ShotEventRow>,
    world_flag: __sdk::TableUpdate<WorldFlagRow>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "avatar_motion" => db_update
                    .avatar_motion
                    .append(avatar_motion_table::parse_table_update(table_update)?),
                "ball" => db_update
                    .ball
                    .append(ball_table::parse_table_update(table_update)?),
                "collected" => db_update
                    .collected
                    .append(collected_table::parse_table_update(table_update)?),
                "completed_course" => db_update
                    .completed_course
                    .append(completed_course_table::parse_table_update(table_update)?),
                "emote_event" => db_update
                    .emote_event
                    .append(emote_event_table::parse_table_update(table_update)?),
                "golf_group" => db_update
                    .golf_group
                    .append(golf_group_table::parse_table_update(table_update)?),
                "hole_score" => db_update
                    .hole_score
                    .append(hole_score_table::parse_table_update(table_update)?),
                "my_account" => db_update
                    .my_account
                    .append(my_account_table::parse_table_update(table_update)?),
                "my_link_code" => db_update
                    .my_link_code
                    .append(my_link_code_table::parse_table_update(table_update)?),
                "my_link_status" => db_update
                    .my_link_status
                    .append(my_link_status_table::parse_table_update(table_update)?),
                "player" => db_update
                    .player
                    .append(player_table::parse_table_update(table_update)?),
                "player_skill" => db_update
                    .player_skill
                    .append(player_skill_table::parse_table_update(table_update)?),
                "room" => db_update
                    .room
                    .append(room_table::parse_table_update(table_update)?),
                "room_member" => db_update
                    .room_member
                    .append(room_member_table::parse_table_update(table_update)?),
                "shot_event" => db_update
                    .shot_event
                    .append(shot_event_table::parse_table_update(table_update)?),
                "world_flag" => db_update
                    .world_flag
                    .append(world_flag_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.avatar_motion = cache
            .apply_diff_to_table::<AvatarMotionRow>("avatar_motion", &self.avatar_motion)
            .with_updates_by_pk(|row| &row.account_id);
        diff.ball = cache
            .apply_diff_to_table::<BallRow>("ball", &self.ball)
            .with_updates_by_pk(|row| &row.account_id);
        diff.collected = cache
            .apply_diff_to_table::<CollectedRow>("collected", &self.collected)
            .with_updates_by_pk(|row| &row.id);
        diff.completed_course = cache
            .apply_diff_to_table::<CompletedCourseRow>("completed_course", &self.completed_course)
            .with_updates_by_pk(|row| &row.id);
        diff.emote_event = self.emote_event.into_event_diff();
        diff.golf_group = cache
            .apply_diff_to_table::<GolfGroupRow>("golf_group", &self.golf_group)
            .with_updates_by_pk(|row| &row.group_id);
        diff.hole_score = cache
            .apply_diff_to_table::<HoleScoreRow>("hole_score", &self.hole_score)
            .with_updates_by_pk(|row| &row.id);
        diff.player = cache
            .apply_diff_to_table::<PlayerRow>("player", &self.player)
            .with_updates_by_pk(|row| &row.account_id);
        diff.player_skill = cache
            .apply_diff_to_table::<PlayerSkillRow>("player_skill", &self.player_skill)
            .with_updates_by_pk(|row| &row.id);
        diff.room = cache
            .apply_diff_to_table::<RoomRow>("room", &self.room)
            .with_updates_by_pk(|row| &row.room_id);
        diff.room_member = cache
            .apply_diff_to_table::<RoomMemberRow>("room_member", &self.room_member)
            .with_updates_by_pk(|row| &row.account_id);
        diff.shot_event = self.shot_event.into_event_diff();
        diff.world_flag = cache
            .apply_diff_to_table::<WorldFlagRow>("world_flag", &self.world_flag)
            .with_updates_by_pk(|row| &row.id);
        diff.my_account = cache.apply_diff_to_table::<PlayerRow>("my_account", &self.my_account);
        diff.my_link_code =
            cache.apply_diff_to_table::<LinkCodeView>("my_link_code", &self.my_link_code);
        diff.my_link_status =
            cache.apply_diff_to_table::<LinkStatus>("my_link_status", &self.my_link_status);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "avatar_motion" => db_update
                    .avatar_motion
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ball" => db_update
                    .ball
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "collected" => db_update
                    .collected
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "completed_course" => db_update
                    .completed_course
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "emote_event" => db_update
                    .emote_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "golf_group" => db_update
                    .golf_group
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "hole_score" => db_update
                    .hole_score
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_account" => db_update
                    .my_account
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_link_code" => db_update
                    .my_link_code
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_link_status" => db_update
                    .my_link_status
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_skill" => db_update
                    .player_skill
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "room" => db_update
                    .room
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "room_member" => db_update
                    .room_member
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "shot_event" => db_update
                    .shot_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "world_flag" => db_update
                    .world_flag
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "avatar_motion" => db_update
                    .avatar_motion
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ball" => db_update
                    .ball
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "collected" => db_update
                    .collected
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "completed_course" => db_update
                    .completed_course
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "emote_event" => db_update
                    .emote_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "golf_group" => db_update
                    .golf_group
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "hole_score" => db_update
                    .hole_score
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_account" => db_update
                    .my_account
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_link_code" => db_update
                    .my_link_code
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_link_status" => db_update
                    .my_link_status
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_skill" => db_update
                    .player_skill
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "room" => db_update
                    .room
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "room_member" => db_update
                    .room_member
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "shot_event" => db_update
                    .shot_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "world_flag" => db_update
                    .world_flag
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    avatar_motion: __sdk::TableAppliedDiff<'r, AvatarMotionRow>,
    ball: __sdk::TableAppliedDiff<'r, BallRow>,
    collected: __sdk::TableAppliedDiff<'r, CollectedRow>,
    completed_course: __sdk::TableAppliedDiff<'r, CompletedCourseRow>,
    emote_event: __sdk::TableAppliedDiff<'r, EmoteEventRow>,
    golf_group: __sdk::TableAppliedDiff<'r, GolfGroupRow>,
    hole_score: __sdk::TableAppliedDiff<'r, HoleScoreRow>,
    my_account: __sdk::TableAppliedDiff<'r, PlayerRow>,
    my_link_code: __sdk::TableAppliedDiff<'r, LinkCodeView>,
    my_link_status: __sdk::TableAppliedDiff<'r, LinkStatus>,
    player: __sdk::TableAppliedDiff<'r, PlayerRow>,
    player_skill: __sdk::TableAppliedDiff<'r, PlayerSkillRow>,
    room: __sdk::TableAppliedDiff<'r, RoomRow>,
    room_member: __sdk::TableAppliedDiff<'r, RoomMemberRow>,
    shot_event: __sdk::TableAppliedDiff<'r, ShotEventRow>,
    world_flag: __sdk::TableAppliedDiff<'r, WorldFlagRow>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<AvatarMotionRow>(
            "avatar_motion",
            &self.avatar_motion,
            event,
        );
        callbacks.invoke_table_row_callbacks::<BallRow>("ball", &self.ball, event);
        callbacks.invoke_table_row_callbacks::<CollectedRow>("collected", &self.collected, event);
        callbacks.invoke_table_row_callbacks::<CompletedCourseRow>(
            "completed_course",
            &self.completed_course,
            event,
        );
        callbacks.invoke_table_row_callbacks::<EmoteEventRow>(
            "emote_event",
            &self.emote_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GolfGroupRow>("golf_group", &self.golf_group, event);
        callbacks.invoke_table_row_callbacks::<HoleScoreRow>("hole_score", &self.hole_score, event);
        callbacks.invoke_table_row_callbacks::<PlayerRow>("my_account", &self.my_account, event);
        callbacks.invoke_table_row_callbacks::<LinkCodeView>(
            "my_link_code",
            &self.my_link_code,
            event,
        );
        callbacks.invoke_table_row_callbacks::<LinkStatus>(
            "my_link_status",
            &self.my_link_status,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlayerRow>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<PlayerSkillRow>(
            "player_skill",
            &self.player_skill,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RoomRow>("room", &self.room, event);
        callbacks.invoke_table_row_callbacks::<RoomMemberRow>(
            "room_member",
            &self.room_member,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ShotEventRow>("shot_event", &self.shot_event, event);
        callbacks.invoke_table_row_callbacks::<WorldFlagRow>("world_flag", &self.world_flag, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        avatar_motion_table::register_table(client_cache);
        ball_table::register_table(client_cache);
        collected_table::register_table(client_cache);
        completed_course_table::register_table(client_cache);
        emote_event_table::register_table(client_cache);
        golf_group_table::register_table(client_cache);
        hole_score_table::register_table(client_cache);
        my_account_table::register_table(client_cache);
        my_link_code_table::register_table(client_cache);
        my_link_status_table::register_table(client_cache);
        player_table::register_table(client_cache);
        player_skill_table::register_table(client_cache);
        room_table::register_table(client_cache);
        room_member_table::register_table(client_cache);
        shot_event_table::register_table(client_cache);
        world_flag_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "avatar_motion",
        "ball",
        "collected",
        "completed_course",
        "emote_event",
        "golf_group",
        "hole_score",
        "my_account",
        "my_link_code",
        "my_link_status",
        "player",
        "player_skill",
        "room",
        "room_member",
        "shot_event",
        "world_flag",
    ];
}
