// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MotionBudgetRow {
    pub account_id: u64,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub mode: u8,
    pub server_time: __sdk::Timestamp,
    pub slack_left: f32,
    pub smoke_at: __sdk::Timestamp,
    pub drink_at: __sdk::Timestamp,
    pub walk_meters_pending: f32,
    pub cart_meters_pending: f32,
    pub drift_meters_pending: f32,
}

impl __sdk::InModule for MotionBudgetRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MotionBudgetRow`.
///
/// Provides typed access to columns for query building.
pub struct MotionBudgetRowCols {
    pub account_id: __sdk::__query_builder::Col<MotionBudgetRow, u64>,
    pub x: __sdk::__query_builder::Col<MotionBudgetRow, f32>,
    pub y: __sdk::__query_builder::Col<MotionBudgetRow, f32>,
    pub z: __sdk::__query_builder::Col<MotionBudgetRow, f32>,
    pub mode: __sdk::__query_builder::Col<MotionBudgetRow, u8>,
    pub server_time: __sdk::__query_builder::Col<MotionBudgetRow, __sdk::Timestamp>,
    pub slack_left: __sdk::__query_builder::Col<MotionBudgetRow, f32>,
    pub smoke_at: __sdk::__query_builder::Col<MotionBudgetRow, __sdk::Timestamp>,
    pub drink_at: __sdk::__query_builder::Col<MotionBudgetRow, __sdk::Timestamp>,
    pub walk_meters_pending: __sdk::__query_builder::Col<MotionBudgetRow, f32>,
    pub cart_meters_pending: __sdk::__query_builder::Col<MotionBudgetRow, f32>,
    pub drift_meters_pending: __sdk::__query_builder::Col<MotionBudgetRow, f32>,
}

impl __sdk::__query_builder::HasCols for MotionBudgetRow {
    type Cols = MotionBudgetRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MotionBudgetRowCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            mode: __sdk::__query_builder::Col::new(table_name, "mode"),
            server_time: __sdk::__query_builder::Col::new(table_name, "server_time"),
            slack_left: __sdk::__query_builder::Col::new(table_name, "slack_left"),
            smoke_at: __sdk::__query_builder::Col::new(table_name, "smoke_at"),
            drink_at: __sdk::__query_builder::Col::new(table_name, "drink_at"),
            walk_meters_pending: __sdk::__query_builder::Col::new(
                table_name,
                "walk_meters_pending",
            ),
            cart_meters_pending: __sdk::__query_builder::Col::new(
                table_name,
                "cart_meters_pending",
            ),
            drift_meters_pending: __sdk::__query_builder::Col::new(
                table_name,
                "drift_meters_pending",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `MotionBudgetRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct MotionBudgetRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<MotionBudgetRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for MotionBudgetRow {
    type IxCols = MotionBudgetRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MotionBudgetRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MotionBudgetRow {}
