// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::link_status_type::LinkStatus;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_link_status`.
///
/// Obtain a handle from the [`MyLinkStatusTableAccess::my_link_status`] method on [`super::RemoteTables`],
/// like `ctx.db.my_link_status()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_link_status().on_insert(...)`.
pub struct MyLinkStatusTableHandle<'ctx> {
    imp: __sdk::TableHandle<LinkStatus>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_link_status`.
pub struct MyLinkStatusTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyLinkStatusTableAccessor {
    type Row = LinkStatus;
    type Handle<'db> = MyLinkStatusTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_link_status()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_link_status`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyLinkStatusTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyLinkStatusTableHandle`], which mediates access to the table `my_link_status`.
    fn my_link_status(&self) -> MyLinkStatusTableHandle<'_>;
}

impl MyLinkStatusTableAccess for super::RemoteTables {
    fn my_link_status(&self) -> MyLinkStatusTableHandle<'_> {
        MyLinkStatusTableHandle {
            imp: self.imp.get_table::<LinkStatus>("my_link_status"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyLinkStatusInsertCallbackId(__sdk::CallbackId);
pub struct MyLinkStatusDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyLinkStatusTableHandle<'ctx> {
    type Row = LinkStatus;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LinkStatus> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyLinkStatusTableHandle<'ctx> {
    type Row = LinkStatus;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LinkStatus> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyLinkStatusInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLinkStatusInsertCallbackId {
        MyLinkStatusInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyLinkStatusInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyLinkStatusDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLinkStatusDeleteCallbackId {
        MyLinkStatusDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyLinkStatusDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyLinkStatusTableHandle<'ctx> {
    type InsertCallbackId = MyLinkStatusInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLinkStatusInsertCallbackId {
        MyLinkStatusInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyLinkStatusInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyLinkStatusTableHandle<'ctx> {
    type DeleteCallbackId = MyLinkStatusDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLinkStatusDeleteCallbackId {
        MyLinkStatusDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyLinkStatusDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LinkStatus>("my_link_status");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LinkStatus>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LinkStatus>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LinkStatus`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_link_statusQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LinkStatus`.
    fn my_link_status(&self) -> __sdk::__query_builder::Table<LinkStatus>;
}

impl my_link_statusQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_link_status(&self) -> __sdk::__query_builder::Table<LinkStatus> {
        __sdk::__query_builder::Table::new("my_link_status")
    }
}
