// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::link_code_view_type::LinkCodeView;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_link_code`.
///
/// Obtain a handle from the [`MyLinkCodeTableAccess::my_link_code`] method on [`super::RemoteTables`],
/// like `ctx.db.my_link_code()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_link_code().on_insert(...)`.
pub struct MyLinkCodeTableHandle<'ctx> {
    imp: __sdk::TableHandle<LinkCodeView>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_link_code`.
pub struct MyLinkCodeTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyLinkCodeTableAccessor {
    type Row = LinkCodeView;
    type Handle<'db> = MyLinkCodeTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_link_code()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_link_code`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyLinkCodeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyLinkCodeTableHandle`], which mediates access to the table `my_link_code`.
    fn my_link_code(&self) -> MyLinkCodeTableHandle<'_>;
}

impl MyLinkCodeTableAccess for super::RemoteTables {
    fn my_link_code(&self) -> MyLinkCodeTableHandle<'_> {
        MyLinkCodeTableHandle {
            imp: self.imp.get_table::<LinkCodeView>("my_link_code"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyLinkCodeInsertCallbackId(__sdk::CallbackId);
pub struct MyLinkCodeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyLinkCodeTableHandle<'ctx> {
    type Row = LinkCodeView;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LinkCodeView> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyLinkCodeTableHandle<'ctx> {
    type Row = LinkCodeView;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LinkCodeView> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyLinkCodeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLinkCodeInsertCallbackId {
        MyLinkCodeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyLinkCodeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyLinkCodeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLinkCodeDeleteCallbackId {
        MyLinkCodeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyLinkCodeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyLinkCodeTableHandle<'ctx> {
    type InsertCallbackId = MyLinkCodeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLinkCodeInsertCallbackId {
        MyLinkCodeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyLinkCodeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyLinkCodeTableHandle<'ctx> {
    type DeleteCallbackId = MyLinkCodeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLinkCodeDeleteCallbackId {
        MyLinkCodeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyLinkCodeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LinkCodeView>("my_link_code");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LinkCodeView>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LinkCodeView>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LinkCodeView`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_link_codeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LinkCodeView`.
    fn my_link_code(&self) -> __sdk::__query_builder::Table<LinkCodeView>;
}

impl my_link_codeQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_link_code(&self) -> __sdk::__query_builder::Table<LinkCodeView> {
        __sdk::__query_builder::Table::new("my_link_code")
    }
}
