// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerSkillRow {
    pub id: u64,
    pub account_id: u64,
    pub skill_id: String,
    pub xp: i32,
}

impl __sdk::InModule for PlayerSkillRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerSkillRow`.
///
/// Provides typed access to columns for query building.
pub struct PlayerSkillRowCols {
    pub id: __sdk::__query_builder::Col<PlayerSkillRow, u64>,
    pub account_id: __sdk::__query_builder::Col<PlayerSkillRow, u64>,
    pub skill_id: __sdk::__query_builder::Col<PlayerSkillRow, String>,
    pub xp: __sdk::__query_builder::Col<PlayerSkillRow, i32>,
}

impl __sdk::__query_builder::HasCols for PlayerSkillRow {
    type Cols = PlayerSkillRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerSkillRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            skill_id: __sdk::__query_builder::Col::new(table_name, "skill_id"),
            xp: __sdk::__query_builder::Col::new(table_name, "xp"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerSkillRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerSkillRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<PlayerSkillRow, u64>,
    pub id: __sdk::__query_builder::IxCol<PlayerSkillRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlayerSkillRow {
    type IxCols = PlayerSkillRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerSkillRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerSkillRow {}
