// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerRow {
    pub account_id: u64,
    pub display_name: String,
    pub name_key: String,
    pub online: bool,
    pub holes_completed: i32,
    pub created_at: __sdk::Timestamp,
    pub last_login: __sdk::Timestamp,
}

impl __sdk::InModule for PlayerRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerRow`.
///
/// Provides typed access to columns for query building.
pub struct PlayerRowCols {
    pub account_id: __sdk::__query_builder::Col<PlayerRow, u64>,
    pub display_name: __sdk::__query_builder::Col<PlayerRow, String>,
    pub name_key: __sdk::__query_builder::Col<PlayerRow, String>,
    pub online: __sdk::__query_builder::Col<PlayerRow, bool>,
    pub holes_completed: __sdk::__query_builder::Col<PlayerRow, i32>,
    pub created_at: __sdk::__query_builder::Col<PlayerRow, __sdk::Timestamp>,
    pub last_login: __sdk::__query_builder::Col<PlayerRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PlayerRow {
    type Cols = PlayerRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerRowCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            name_key: __sdk::__query_builder::Col::new(table_name, "name_key"),
            online: __sdk::__query_builder::Col::new(table_name, "online"),
            holes_completed: __sdk::__query_builder::Col::new(table_name, "holes_completed"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_login: __sdk::__query_builder::Col::new(table_name, "last_login"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<PlayerRow, u64>,
    pub name_key: __sdk::__query_builder::IxCol<PlayerRow, String>,
}

impl __sdk::__query_builder::HasIxCols for PlayerRow {
    type IxCols = PlayerRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            name_key: __sdk::__query_builder::IxCol::new(table_name, "name_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerRow {}
