// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RedeemLinkCodeArgs {
    pub typed_code: String,
}

impl From<RedeemLinkCodeArgs> for super::Reducer {
    fn from(args: RedeemLinkCodeArgs) -> Self {
        Self::RedeemLinkCode {
            typed_code: args.typed_code,
        }
    }
}

impl __sdk::InModule for RedeemLinkCodeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `redeem_link_code`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait redeem_link_code {
    /// Request that the remote module invoke the reducer `redeem_link_code` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`redeem_link_code:redeem_link_code_then`] to run a callback after the reducer completes.
    fn redeem_link_code(&self, typed_code: String) -> __sdk::Result<()> {
        self.redeem_link_code_then(typed_code, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `redeem_link_code` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn redeem_link_code_then(
        &self,
        typed_code: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl redeem_link_code for super::RemoteReducers {
    fn redeem_link_code_then(
        &self,
        typed_code: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RedeemLinkCodeArgs { typed_code }, callback)
    }
}
