// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RoomMemberRow {
    pub account_id: u64,
    pub room_id: u64,
    pub group_id: u64,
    pub zone: i32,
    pub hole_started_at: __sdk::Timestamp,
    pub round_strokes: Vec<i32>,
}

impl __sdk::InModule for RoomMemberRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RoomMemberRow`.
///
/// Provides typed access to columns for query building.
pub struct RoomMemberRowCols {
    pub account_id: __sdk::__query_builder::Col<RoomMemberRow, u64>,
    pub room_id: __sdk::__query_builder::Col<RoomMemberRow, u64>,
    pub group_id: __sdk::__query_builder::Col<RoomMemberRow, u64>,
    pub zone: __sdk::__query_builder::Col<RoomMemberRow, i32>,
    pub hole_started_at: __sdk::__query_builder::Col<RoomMemberRow, __sdk::Timestamp>,
    pub round_strokes: __sdk::__query_builder::Col<RoomMemberRow, Vec<i32>>,
}

impl __sdk::__query_builder::HasCols for RoomMemberRow {
    type Cols = RoomMemberRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RoomMemberRowCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            group_id: __sdk::__query_builder::Col::new(table_name, "group_id"),
            zone: __sdk::__query_builder::Col::new(table_name, "zone"),
            hole_started_at: __sdk::__query_builder::Col::new(table_name, "hole_started_at"),
            round_strokes: __sdk::__query_builder::Col::new(table_name, "round_strokes"),
        }
    }
}

/// Indexed column accessor struct for the table `RoomMemberRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct RoomMemberRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<RoomMemberRow, u64>,
    pub room_id: __sdk::__query_builder::IxCol<RoomMemberRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for RoomMemberRow {
    type IxCols = RoomMemberRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RoomMemberRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RoomMemberRow {}
