// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RoomRow {
    pub room_id: u64,
    pub course_id: String,
    pub player_count: i32,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for RoomRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RoomRow`.
///
/// Provides typed access to columns for query building.
pub struct RoomRowCols {
    pub room_id: __sdk::__query_builder::Col<RoomRow, u64>,
    pub course_id: __sdk::__query_builder::Col<RoomRow, String>,
    pub player_count: __sdk::__query_builder::Col<RoomRow, i32>,
    pub created_at: __sdk::__query_builder::Col<RoomRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for RoomRow {
    type Cols = RoomRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RoomRowCols {
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            course_id: __sdk::__query_builder::Col::new(table_name, "course_id"),
            player_count: __sdk::__query_builder::Col::new(table_name, "player_count"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `RoomRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct RoomRowIxCols {
    pub course_id: __sdk::__query_builder::IxCol<RoomRow, String>,
    pub room_id: __sdk::__query_builder::IxCol<RoomRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for RoomRow {
    type IxCols = RoomRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RoomRowIxCols {
            course_id: __sdk::__query_builder::IxCol::new(table_name, "course_id"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RoomRow {}
