// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::room_member_row_type::RoomMemberRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `room_member`.
///
/// Obtain a handle from the [`RoomMemberTableAccess::room_member`] method on [`super::RemoteTables`],
/// like `ctx.db.room_member()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.room_member().on_insert(...)`.
pub struct RoomMemberTableHandle<'ctx> {
    imp: __sdk::TableHandle<RoomMemberRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `room_member`.
pub struct RoomMemberTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for RoomMemberTableAccessor {
    type Row = RoomMemberRow;
    type Handle<'db> = RoomMemberTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.room_member()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `room_member`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RoomMemberTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RoomMemberTableHandle`], which mediates access to the table `room_member`.
    fn room_member(&self) -> RoomMemberTableHandle<'_>;
}

impl RoomMemberTableAccess for super::RemoteTables {
    fn room_member(&self) -> RoomMemberTableHandle<'_> {
        RoomMemberTableHandle {
            imp: self.imp.get_table::<RoomMemberRow>("room_member"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RoomMemberInsertCallbackId(__sdk::CallbackId);
pub struct RoomMemberDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RoomMemberTableHandle<'ctx> {
    type Row = RoomMemberRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RoomMemberRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for RoomMemberTableHandle<'ctx> {
    type Row = RoomMemberRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RoomMemberRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RoomMemberInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoomMemberInsertCallbackId {
        RoomMemberInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RoomMemberInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RoomMemberDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoomMemberDeleteCallbackId {
        RoomMemberDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RoomMemberDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RoomMemberTableHandle<'ctx> {
    type InsertCallbackId = RoomMemberInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoomMemberInsertCallbackId {
        RoomMemberInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RoomMemberInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RoomMemberTableHandle<'ctx> {
    type DeleteCallbackId = RoomMemberDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoomMemberDeleteCallbackId {
        RoomMemberDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RoomMemberDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RoomMemberUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RoomMemberTableHandle<'ctx> {
    type UpdateCallbackId = RoomMemberUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RoomMemberUpdateCallbackId {
        RoomMemberUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RoomMemberUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RoomMemberTableHandle<'ctx> {
    type UpdateCallbackId = RoomMemberUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RoomMemberUpdateCallbackId {
        RoomMemberUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RoomMemberUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `account_id` unique index on the table `room_member`,
/// which allows point queries on the field of the same name
/// via the [`RoomMemberAccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.room_member().account_id().find(...)`.
pub struct RoomMemberAccountIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RoomMemberRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RoomMemberTableHandle<'ctx> {
    /// Get a handle on the `account_id` unique index on the table `room_member`.
    pub fn account_id(&self) -> RoomMemberAccountIdUnique<'ctx> {
        RoomMemberAccountIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("account_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RoomMemberAccountIdUnique<'ctx> {
    /// Find the subscribed row whose `account_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RoomMemberRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RoomMemberRow>("room_member");
    _table.add_unique_constraint::<u64>("account_id", |row| &row.account_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RoomMemberRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RoomMemberRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RoomMemberRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait room_memberQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RoomMemberRow`.
    fn room_member(&self) -> __sdk::__query_builder::Table<RoomMemberRow>;
}

impl room_memberQueryTableAccess for __sdk::QueryTableAccessor {
    fn room_member(&self) -> __sdk::__query_builder::Table<RoomMemberRow> {
        __sdk::__query_builder::Table::new("room_member")
    }
}
