// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::room_row_type::RoomRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `room`.
///
/// Obtain a handle from the [`RoomTableAccess::room`] method on [`super::RemoteTables`],
/// like `ctx.db.room()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.room().on_insert(...)`.
pub struct RoomTableHandle<'ctx> {
    imp: __sdk::TableHandle<RoomRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `room`.
pub struct RoomTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for RoomTableAccessor {
    type Row = RoomRow;
    type Handle<'db> = RoomTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.room()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `room`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RoomTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RoomTableHandle`], which mediates access to the table `room`.
    fn room(&self) -> RoomTableHandle<'_>;
}

impl RoomTableAccess for super::RemoteTables {
    fn room(&self) -> RoomTableHandle<'_> {
        RoomTableHandle {
            imp: self.imp.get_table::<RoomRow>("room"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RoomInsertCallbackId(__sdk::CallbackId);
pub struct RoomDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RoomTableHandle<'ctx> {
    type Row = RoomRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RoomRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for RoomTableHandle<'ctx> {
    type Row = RoomRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RoomRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RoomInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoomInsertCallbackId {
        RoomInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RoomInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RoomDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoomDeleteCallbackId {
        RoomDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RoomDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RoomTableHandle<'ctx> {
    type InsertCallbackId = RoomInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoomInsertCallbackId {
        RoomInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RoomInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RoomTableHandle<'ctx> {
    type DeleteCallbackId = RoomDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoomDeleteCallbackId {
        RoomDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RoomDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RoomUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RoomTableHandle<'ctx> {
    type UpdateCallbackId = RoomUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RoomUpdateCallbackId {
        RoomUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RoomUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RoomTableHandle<'ctx> {
    type UpdateCallbackId = RoomUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RoomUpdateCallbackId {
        RoomUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RoomUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `room_id` unique index on the table `room`,
/// which allows point queries on the field of the same name
/// via the [`RoomRoomIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.room().room_id().find(...)`.
pub struct RoomRoomIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RoomRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RoomTableHandle<'ctx> {
    /// Get a handle on the `room_id` unique index on the table `room`.
    pub fn room_id(&self) -> RoomRoomIdUnique<'ctx> {
        RoomRoomIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("room_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RoomRoomIdUnique<'ctx> {
    /// Find the subscribed row whose `room_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RoomRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RoomRow>("room");
    _table.add_unique_constraint::<u64>("room_id", |row| &row.room_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RoomRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RoomRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RoomRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait roomQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RoomRow`.
    fn room(&self) -> __sdk::__query_builder::Table<RoomRow>;
}

impl roomQueryTableAccess for __sdk::QueryTableAccessor {
    fn room(&self) -> __sdk::__query_builder::Table<RoomRow> {
        __sdk::__query_builder::Table::new("room")
    }
}
