// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::server_protocol_info_type::ServerProtocolInfo;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `server_protocol`.
///
/// Obtain a handle from the [`ServerProtocolTableAccess::server_protocol`] method on [`super::RemoteTables`],
/// like `ctx.db.server_protocol()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.server_protocol().on_insert(...)`.
pub struct ServerProtocolTableHandle<'ctx> {
    imp: __sdk::TableHandle<ServerProtocolInfo>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `server_protocol`.
pub struct ServerProtocolTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ServerProtocolTableAccessor {
    type Row = ServerProtocolInfo;
    type Handle<'db> = ServerProtocolTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.server_protocol()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `server_protocol`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ServerProtocolTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ServerProtocolTableHandle`], which mediates access to the table `server_protocol`.
    fn server_protocol(&self) -> ServerProtocolTableHandle<'_>;
}

impl ServerProtocolTableAccess for super::RemoteTables {
    fn server_protocol(&self) -> ServerProtocolTableHandle<'_> {
        ServerProtocolTableHandle {
            imp: self.imp.get_table::<ServerProtocolInfo>("server_protocol"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ServerProtocolInsertCallbackId(__sdk::CallbackId);
pub struct ServerProtocolDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ServerProtocolTableHandle<'ctx> {
    type Row = ServerProtocolInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ServerProtocolInfo> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ServerProtocolTableHandle<'ctx> {
    type Row = ServerProtocolInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ServerProtocolInfo> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ServerProtocolInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerProtocolInsertCallbackId {
        ServerProtocolInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ServerProtocolInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ServerProtocolDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerProtocolDeleteCallbackId {
        ServerProtocolDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ServerProtocolDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ServerProtocolTableHandle<'ctx> {
    type InsertCallbackId = ServerProtocolInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerProtocolInsertCallbackId {
        ServerProtocolInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ServerProtocolInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ServerProtocolTableHandle<'ctx> {
    type DeleteCallbackId = ServerProtocolDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerProtocolDeleteCallbackId {
        ServerProtocolDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ServerProtocolDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ServerProtocolInfo>("server_protocol");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ServerProtocolInfo>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ServerProtocolInfo>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ServerProtocolInfo`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait server_protocolQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ServerProtocolInfo`.
    fn server_protocol(&self) -> __sdk::__query_builder::Table<ServerProtocolInfo>;
}

impl server_protocolQueryTableAccess for __sdk::QueryTableAccessor {
    fn server_protocol(&self) -> __sdk::__query_builder::Table<ServerProtocolInfo> {
        __sdk::__query_builder::Table::new("server_protocol")
    }
}
