// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ServerConfigRow {
    pub id: u32,
    pub owner: __sdk::Identity,
    pub auth_issuer: String,
    pub auth_audience: String,
    pub allow_anonymous: bool,
    pub steam_app_id: u32,
    pub allow_non_steam: bool,
    pub link_secret: String,
}

impl __sdk::InModule for ServerConfigRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ServerConfigRow`.
///
/// Provides typed access to columns for query building.
pub struct ServerConfigRowCols {
    pub id: __sdk::__query_builder::Col<ServerConfigRow, u32>,
    pub owner: __sdk::__query_builder::Col<ServerConfigRow, __sdk::Identity>,
    pub auth_issuer: __sdk::__query_builder::Col<ServerConfigRow, String>,
    pub auth_audience: __sdk::__query_builder::Col<ServerConfigRow, String>,
    pub allow_anonymous: __sdk::__query_builder::Col<ServerConfigRow, bool>,
    pub steam_app_id: __sdk::__query_builder::Col<ServerConfigRow, u32>,
    pub allow_non_steam: __sdk::__query_builder::Col<ServerConfigRow, bool>,
    pub link_secret: __sdk::__query_builder::Col<ServerConfigRow, String>,
}

impl __sdk::__query_builder::HasCols for ServerConfigRow {
    type Cols = ServerConfigRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ServerConfigRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            auth_issuer: __sdk::__query_builder::Col::new(table_name, "auth_issuer"),
            auth_audience: __sdk::__query_builder::Col::new(table_name, "auth_audience"),
            allow_anonymous: __sdk::__query_builder::Col::new(table_name, "allow_anonymous"),
            steam_app_id: __sdk::__query_builder::Col::new(table_name, "steam_app_id"),
            allow_non_steam: __sdk::__query_builder::Col::new(table_name, "allow_non_steam"),
            link_secret: __sdk::__query_builder::Col::new(table_name, "link_secret"),
        }
    }
}

/// Indexed column accessor struct for the table `ServerConfigRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct ServerConfigRowIxCols {
    pub id: __sdk::__query_builder::IxCol<ServerConfigRow, u32>,
}

impl __sdk::__query_builder::HasIxCols for ServerConfigRow {
    type IxCols = ServerConfigRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ServerConfigRowIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ServerConfigRow {}
