// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SessionRow {
    pub account_id: u64,
    pub identity: __sdk::Identity,
    pub connection_id: __sdk::ConnectionId,
}

impl __sdk::InModule for SessionRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SessionRow`.
///
/// Provides typed access to columns for query building.
pub struct SessionRowCols {
    pub account_id: __sdk::__query_builder::Col<SessionRow, u64>,
    pub identity: __sdk::__query_builder::Col<SessionRow, __sdk::Identity>,
    pub connection_id: __sdk::__query_builder::Col<SessionRow, __sdk::ConnectionId>,
}

impl __sdk::__query_builder::HasCols for SessionRow {
    type Cols = SessionRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SessionRowCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            connection_id: __sdk::__query_builder::Col::new(table_name, "connection_id"),
        }
    }
}

/// Indexed column accessor struct for the table `SessionRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct SessionRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<SessionRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for SessionRow {
    type IxCols = SessionRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SessionRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SessionRow {}
