// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::shot_event_row_type::ShotEventRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `shot_event`.
///
/// Obtain a handle from the [`ShotEventTableAccess::shot_event`] method on [`super::RemoteTables`],
/// like `ctx.db.shot_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.shot_event().on_insert(...)`.
pub struct ShotEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShotEventRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `shot_event`.
pub struct ShotEventTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ShotEventTableAccessor {
    type Row = ShotEventRow;
    type Handle<'db> = ShotEventTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.shot_event()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `shot_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShotEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShotEventTableHandle`], which mediates access to the table `shot_event`.
    fn shot_event(&self) -> ShotEventTableHandle<'_>;
}

impl ShotEventTableAccess for super::RemoteTables {
    fn shot_event(&self) -> ShotEventTableHandle<'_> {
        ShotEventTableHandle {
            imp: self.imp.get_table::<ShotEventRow>("shot_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShotEventInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ShotEventTableHandle<'ctx> {
    type Row = ShotEventRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShotEventRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::EventTable for ShotEventTableHandle<'ctx> {
    type Row = ShotEventRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShotEventRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShotEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShotEventInsertCallbackId {
        ShotEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShotEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ShotEventTableHandle<'ctx> {
    type InsertCallbackId = ShotEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShotEventInsertCallbackId {
        ShotEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShotEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShotEventRow>("shot_event");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ShotEventRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShotEventRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ShotEventRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait shot_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ShotEventRow`.
    fn shot_event(&self) -> __sdk::__query_builder::Table<ShotEventRow>;
}

impl shot_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn shot_event(&self) -> __sdk::__query_builder::Table<ShotEventRow> {
        __sdk::__query_builder::Table::new("shot_event")
    }
}
