// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShotEventRow {
    pub room_id: u64,
    pub account_id: u64,
    pub zone: i32,
    pub stroke: i32,
    pub start_x: f32,
    pub start_y: f32,
    pub start_z: f32,
    pub aim_angle: f32,
    pub club_id: String,
    pub power: f32,
    pub cigarette_active: bool,
    pub wind_time: f32,
    pub rest_x: f32,
    pub rest_y: f32,
    pub rest_z: f32,
    pub holed: bool,
}

impl __sdk::InModule for ShotEventRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ShotEventRow`.
///
/// Provides typed access to columns for query building.
pub struct ShotEventRowCols {
    pub room_id: __sdk::__query_builder::Col<ShotEventRow, u64>,
    pub account_id: __sdk::__query_builder::Col<ShotEventRow, u64>,
    pub zone: __sdk::__query_builder::Col<ShotEventRow, i32>,
    pub stroke: __sdk::__query_builder::Col<ShotEventRow, i32>,
    pub start_x: __sdk::__query_builder::Col<ShotEventRow, f32>,
    pub start_y: __sdk::__query_builder::Col<ShotEventRow, f32>,
    pub start_z: __sdk::__query_builder::Col<ShotEventRow, f32>,
    pub aim_angle: __sdk::__query_builder::Col<ShotEventRow, f32>,
    pub club_id: __sdk::__query_builder::Col<ShotEventRow, String>,
    pub power: __sdk::__query_builder::Col<ShotEventRow, f32>,
    pub cigarette_active: __sdk::__query_builder::Col<ShotEventRow, bool>,
    pub wind_time: __sdk::__query_builder::Col<ShotEventRow, f32>,
    pub rest_x: __sdk::__query_builder::Col<ShotEventRow, f32>,
    pub rest_y: __sdk::__query_builder::Col<ShotEventRow, f32>,
    pub rest_z: __sdk::__query_builder::Col<ShotEventRow, f32>,
    pub holed: __sdk::__query_builder::Col<ShotEventRow, bool>,
}

impl __sdk::__query_builder::HasCols for ShotEventRow {
    type Cols = ShotEventRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShotEventRowCols {
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            zone: __sdk::__query_builder::Col::new(table_name, "zone"),
            stroke: __sdk::__query_builder::Col::new(table_name, "stroke"),
            start_x: __sdk::__query_builder::Col::new(table_name, "start_x"),
            start_y: __sdk::__query_builder::Col::new(table_name, "start_y"),
            start_z: __sdk::__query_builder::Col::new(table_name, "start_z"),
            aim_angle: __sdk::__query_builder::Col::new(table_name, "aim_angle"),
            club_id: __sdk::__query_builder::Col::new(table_name, "club_id"),
            power: __sdk::__query_builder::Col::new(table_name, "power"),
            cigarette_active: __sdk::__query_builder::Col::new(table_name, "cigarette_active"),
            wind_time: __sdk::__query_builder::Col::new(table_name, "wind_time"),
            rest_x: __sdk::__query_builder::Col::new(table_name, "rest_x"),
            rest_y: __sdk::__query_builder::Col::new(table_name, "rest_y"),
            rest_z: __sdk::__query_builder::Col::new(table_name, "rest_z"),
            holed: __sdk::__query_builder::Col::new(table_name, "holed"),
        }
    }
}

/// Indexed column accessor struct for the table `ShotEventRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShotEventRowIxCols {
    pub room_id: __sdk::__query_builder::IxCol<ShotEventRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for ShotEventRow {
    type IxCols = ShotEventRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShotEventRowIxCols {
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}
