// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TakeShotArgs {
    pub stroke: i32,
    pub aim_angle: f32,
    pub club_id: String,
    pub power: f32,
    pub cigarette_active: bool,
    pub wind_time: f32,
}

impl From<TakeShotArgs> for super::Reducer {
    fn from(args: TakeShotArgs) -> Self {
        Self::TakeShot {
            stroke: args.stroke,
            aim_angle: args.aim_angle,
            club_id: args.club_id,
            power: args.power,
            cigarette_active: args.cigarette_active,
            wind_time: args.wind_time,
        }
    }
}

impl __sdk::InModule for TakeShotArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `take_shot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait take_shot {
    /// Request that the remote module invoke the reducer `take_shot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`take_shot:take_shot_then`] to run a callback after the reducer completes.
    fn take_shot(
        &self,
        stroke: i32,
        aim_angle: f32,
        club_id: String,
        power: f32,
        cigarette_active: bool,
        wind_time: f32,
    ) -> __sdk::Result<()> {
        self.take_shot_then(
            stroke,
            aim_angle,
            club_id,
            power,
            cigarette_active,
            wind_time,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `take_shot` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn take_shot_then(
        &self,
        stroke: i32,
        aim_angle: f32,
        club_id: String,
        power: f32,
        cigarette_active: bool,
        wind_time: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl take_shot for super::RemoteReducers {
    fn take_shot_then(
        &self,
        stroke: i32,
        aim_angle: f32,
        club_id: String,
        power: f32,
        cigarette_active: bool,
        wind_time: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TakeShotArgs {
                stroke,
                aim_angle,
                club_id,
                power,
                cigarette_active,
                wind_time,
            },
            callback,
        )
    }
}
