// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateMotionArgs {
    pub zone: i32,
    pub mode: u8,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
    pub speed: f32,
    pub turn_rate: f32,
    pub client_time: f64,
}

impl From<UpdateMotionArgs> for super::Reducer {
    fn from(args: UpdateMotionArgs) -> Self {
        Self::UpdateMotion {
            zone: args.zone,
            mode: args.mode,
            x: args.x,
            y: args.y,
            z: args.z,
            yaw: args.yaw,
            speed: args.speed,
            turn_rate: args.turn_rate,
            client_time: args.client_time,
        }
    }
}

impl __sdk::InModule for UpdateMotionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_motion`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_motion {
    /// Request that the remote module invoke the reducer `update_motion` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_motion:update_motion_then`] to run a callback after the reducer completes.
    fn update_motion(
        &self,
        zone: i32,
        mode: u8,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,
        speed: f32,
        turn_rate: f32,
        client_time: f64,
    ) -> __sdk::Result<()> {
        self.update_motion_then(
            zone,
            mode,
            x,
            y,
            z,
            yaw,
            speed,
            turn_rate,
            client_time,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `update_motion` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_motion_then(
        &self,
        zone: i32,
        mode: u8,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,
        speed: f32,
        turn_rate: f32,
        client_time: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_motion for super::RemoteReducers {
    fn update_motion_then(
        &self,
        zone: i32,
        mode: u8,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,
        speed: f32,
        turn_rate: f32,
        client_time: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateMotionArgs {
                zone,
                mode,
                x,
                y,
                z,
                yaw,
                speed,
                turn_rate,
                client_time,
            },
            callback,
        )
    }
}
