// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_flag_row_type::WorldFlagRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_flag`.
///
/// Obtain a handle from the [`WorldFlagTableAccess::world_flag`] method on [`super::RemoteTables`],
/// like `ctx.db.world_flag()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_flag().on_insert(...)`.
pub struct WorldFlagTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldFlagRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `world_flag`.
pub struct WorldFlagTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for WorldFlagTableAccessor {
    type Row = WorldFlagRow;
    type Handle<'db> = WorldFlagTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.world_flag()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_flag`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldFlagTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldFlagTableHandle`], which mediates access to the table `world_flag`.
    fn world_flag(&self) -> WorldFlagTableHandle<'_>;
}

impl WorldFlagTableAccess for super::RemoteTables {
    fn world_flag(&self) -> WorldFlagTableHandle<'_> {
        WorldFlagTableHandle {
            imp: self.imp.get_table::<WorldFlagRow>("world_flag"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldFlagInsertCallbackId(__sdk::CallbackId);
pub struct WorldFlagDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for WorldFlagTableHandle<'ctx> {
    type Row = WorldFlagRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldFlagRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for WorldFlagTableHandle<'ctx> {
    type Row = WorldFlagRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldFlagRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldFlagInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldFlagInsertCallbackId {
        WorldFlagInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldFlagInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldFlagDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldFlagDeleteCallbackId {
        WorldFlagDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldFlagDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for WorldFlagTableHandle<'ctx> {
    type InsertCallbackId = WorldFlagInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldFlagInsertCallbackId {
        WorldFlagInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldFlagInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for WorldFlagTableHandle<'ctx> {
    type DeleteCallbackId = WorldFlagDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldFlagDeleteCallbackId {
        WorldFlagDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldFlagDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldFlagUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldFlagTableHandle<'ctx> {
    type UpdateCallbackId = WorldFlagUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldFlagUpdateCallbackId {
        WorldFlagUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldFlagUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for WorldFlagTableHandle<'ctx> {
    type UpdateCallbackId = WorldFlagUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldFlagUpdateCallbackId {
        WorldFlagUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldFlagUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `world_flag`,
/// which allows point queries on the field of the same name
/// via the [`WorldFlagIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_flag().id().find(...)`.
pub struct WorldFlagIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldFlagRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldFlagTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `world_flag`.
    pub fn id(&self) -> WorldFlagIdUnique<'ctx> {
        WorldFlagIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldFlagIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WorldFlagRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldFlagRow>("world_flag");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldFlagRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldFlagRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldFlagRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_flagQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldFlagRow`.
    fn world_flag(&self) -> __sdk::__query_builder::Table<WorldFlagRow>;
}

impl world_flagQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_flag(&self) -> __sdk::__query_builder::Table<WorldFlagRow> {
        __sdk::__query_builder::Table::new("world_flag")
    }
}
