// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldFlagRow {
    pub id: u64,
    pub account_id: u64,
    pub flag: String,
}

impl __sdk::InModule for WorldFlagRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WorldFlagRow`.
///
/// Provides typed access to columns for query building.
pub struct WorldFlagRowCols {
    pub id: __sdk::__query_builder::Col<WorldFlagRow, u64>,
    pub account_id: __sdk::__query_builder::Col<WorldFlagRow, u64>,
    pub flag: __sdk::__query_builder::Col<WorldFlagRow, String>,
}

impl __sdk::__query_builder::HasCols for WorldFlagRow {
    type Cols = WorldFlagRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldFlagRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            flag: __sdk::__query_builder::Col::new(table_name, "flag"),
        }
    }
}

/// Indexed column accessor struct for the table `WorldFlagRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldFlagRowIxCols {
    pub account_id: __sdk::__query_builder::IxCol<WorldFlagRow, u64>,
    pub id: __sdk::__query_builder::IxCol<WorldFlagRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for WorldFlagRow {
    type IxCols = WorldFlagRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldFlagRowIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WorldFlagRow {}
