# Writes OUTPUT: a C++ file holding every JSON file of the content directories
# in DIRECTORIES (relative to ASSET_ROOT) as string literals, keyed by their
# path relative to ASSET_ROOT. Run in script mode:
#   cmake -DASSET_ROOT=... -DDIRECTORIES=holes;courses -DOUTPUT=... -P embed_content.cmake

set(delimiter "golfpp_embed")
set(entries "")
set(literals "")
set(count 0)
foreach(directory IN LISTS DIRECTORIES)
    file(GLOB files LIST_DIRECTORIES false "${ASSET_ROOT}/${directory}/*.json")
    list(SORT files)
    foreach(path IN LISTS files)
        file(RELATIVE_PATH relative "${ASSET_ROOT}" "${path}")
        file(READ "${path}" text)
        string(FIND "${text}" ")${delimiter}\"" clash)
        if (NOT clash EQUAL -1)
            message(FATAL_ERROR "${relative} contains the raw string delimiter ${delimiter}")
        endif()
        string(APPEND literals "constexpr char file_${count}[] = R\"${delimiter}(${text})${delimiter}\";\n")
        string(APPEND entries "    {\"${relative}\", std::string_view(file_${count}, sizeof(file_${count}) - 1)},\n")
        math(EXPR count "${count} + 1")
    endforeach()
endforeach()

set(source "// Generated by server/golfpp_module/embed_content.cmake. Do not edit.\n\n")
string(APPEND source "#include \"embedded_content.h\"\n\n")
string(APPEND source "namespace {\n${literals}}\n\n")
string(APPEND source "const embedded_file embedded_files[] = {\n${entries}};\n")
string(APPEND source "const std::size_t embedded_file_count = ${count};\n")

# Only rewrite when something changed, so the module does not rebuild needlessly.
if (EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
    if (previous STREQUAL source)
        file(TOUCH_NOCREATE "${OUTPUT}")
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${source}")
